repos:
	- repo: https://github.com/pre-commit/pre-commit-hooks
		rev: v4.5.0
		hooks:
			- id: trailing-whitespace
			- id: end-of-file-fixer
			- id: check-yaml
			- id: debug-statements

	# Auto-formatters (run first)
	- repo: https://github.com/psf/black
		rev: 24.3.0
		hooks:
			- id: black
				args: [--line-length=88]

	- repo: https://github.com/pycqa/isort
		rev: 5.13.2
		hooks:
			- id: isort
				args: ["--profile", "black"]

	# Autocorrect unused imports/variables
	- repo: https://github.com/PyCQA/autoflake
		rev: v2.2.1
		hooks:
			- id: autoflake
				args: [
					"--in-place",
					"--remove-unused-variables",
					"--remove-all-unused-imports",
					"--ignore-init-module-imports"
				]

	# Modernize Python syntax
	- repo: https://github.com/asottile/pyupgrade
		rev: v3.15.1
		hooks:
			- id: pyupgrade
				args: ["--py39-plus"]

	# Linters (run after autofix)
	- repo: https://github.com/pycqa/flake8
		rev: 7.0.0
		hooks:
			- id: flake8
				additional_dependencies: [flake8-bugbear==24.2.6]
