version: '3.8'
services:
  southoftethys:
    build:
      context: .
      dockerfile: Dockerfile
    image: southoftethys
  command: sh -c "python utils/lint_story.py && python utils/generate_timeline_mermaid.py && python utils/generate_timeline.py && python utils/generate_map.py && python utils/evolve_species.py # && python utils/snippet_processor.py # && python utils/hometown.py"
