version: '3.8'
services:
  southoftethys:
    build:
      context: .
      dockerfile: Dockerfile
    image: southoftethys
    command: >
      sh -c "pip install debugpy && python -m debugpy --wait-for-client --listen 0.0.0.0:5678 utils/generate_timeline.py"
    ports:
      - 5678:5678

