"""Draw who canon remembers: the people, what they were present at, and who claims them.

The fourth generated view, and the last one the book was missing. The timeline says *when*,
the atlas says *where*, and this says *who* -- 51 characters joined to the 28 events they
appear in, grouped by the factions and cultures that hold them.

**One graph per epoch, mirroring the atlas.** Not because Mermaid cannot hold the whole thing
-- 82 nodes today against a ceiling near a hundred, so it very nearly can -- but because a
picture of everyone who ever lived is not a picture of anything. Sliced, the largest era is 37
nodes and the smallest is 6, and each one is a cast list you can actually read. The whole-graph
version would also fall over on the next chapter, and it would do it silently, by laying out
into an unreadable mat rather than by failing.

Grouping is by faction where a character has one and by culture otherwise, because Mermaid
subgraphs cannot overlap and a person has both. Three factions claim 13 of 51 characters; the
remaining 38 group by culture, of which there are 25. That asymmetry is real and worth seeing:
canon has many peoples and very few organisations.

**A character with no events still draws.** Eleven of the 51 appear in nothing yet, and they
render as unconnected nodes inside their group rather than being dropped. That is the same
call the timeline made for its four edgeless events: the gap is the authoring backlog made
visible, and hiding it would make a tidier diagram and a less true one.
"""

from __future__ import annotations

import argparse
import collections
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from book_nav import nav
from canon_epochs import in_era, load_epochs

# Windows consoles default to cp1252, which cannot encode the status glyphs below.
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

BASE = Path(__file__).resolve().parent.parent
DB = BASE / "database"
OUT_DIR = BASE / "docs"
OUT_MD = OUT_DIR / "memory_map.md"

# The fields an event uses to say a person was there. `participants` is the common one;
# the other two appear on a handful of events and mean the same thing for this purpose.
PRESENT_AT = ("participants", "witnesses", "actors")


def label(text: str) -> str:
    """Mermaid reads brackets and quotes as syntax, so a name carrying them breaks the graph."""
    return (text or "").replace('"', "'").replace("[", "(").replace("]", ")")


def node_id(entity_id: str) -> str:
    """Mermaid node ids may not carry the punctuation canon's ids do not carry anyway."""
    return entity_id.replace("-", "_")


def load(folder: str) -> list[dict]:
    d = DB / folder
    if not d.exists():
        return []
    out = []
    for f in sorted(d.glob("*.json")):
        payload = json.loads(f.read_text(encoding="utf-8"))
        if not payload.get("sample"):
            out.append(payload)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--era", help="render one epoch only, by id")
    args = ap.parse_args()

    characters = {c["id"]: c for c in load("characters")}
    events = {e["id"]: e for e in load("events")}
    factions = load("factions")

    # Who claims whom. The faction owns the membership list and a character does not name one
    # back -- one owner, so the two cannot drift apart the way a mirrored pair can.
    claims: dict[str, dict] = {}
    for f in factions:
        for member in f.get("members", []) or []:
            if member in characters:
                claims[member] = f

    # Who was present at what.
    appears: dict[str, set[str]] = collections.defaultdict(set)
    for eid, event in events.items():
        for field in PRESENT_AT:
            for who in event.get(field, []) or []:
                if who in characters:
                    appears[who].add(eid)

    epochs = load_epochs()
    if args.era:
        epochs = [e for e in epochs if e["id"] == args.era]
        if not epochs:
            print(f"No such epoch: {args.era}")
            return 1

    doc: list[str] = [
        "# The Memory Map",
        "",
        nav("memory_map.md"),
        "",
        "*Generated by `utils/generate_memory_map.py`. Do not edit by hand.*",
        "",
        "Who canon remembers, one era at a time: the people, the events they were present at,",
        "and the factions and cultures that hold them. The timeline says when and the atlas says",
        "where; this says who.",
        "",
        "Grouping is by faction where someone has one and by culture otherwise, because a person",
        "has both and the boxes cannot overlap. A character who appears in no event yet still",
        "draws, unconnected, rather than being left out.",
        "",
    ]

    drawn = 0
    for epoch in epochs:
        # A character belongs to an era if canon dates them to it *or* if they are present at
        # something that happens in it. Dating alone was the first version and it drew the
        # Post-Cataclysm as empty: the Survival Train happens there and its three participants
        # -- Varuna, Mitra and Guyuk -- are dated to the Current era and the Migrations, because
        # `epoch` says when someone first appears rather than the only era they may act in.
        # Varuna walking into the era after the Shattering is the game's whole premise.
        acts_here = {who for eid, event in events.items()
                     if event.get("epoch") == epoch["id"]
                     for field in PRESENT_AT for who in (event.get(field) or [])
                     if who in characters}
        here = [c for c in characters.values()
                if in_era(c, epoch["id"]) or c["id"] in acts_here]
        # This era's events only, and only the ones somebody here attended. Drawing every event
        # a person was ever present at was the first version: the Post-Cataclysm graph then
        # carried the Botai Cattle Raid, which happens two eras earlier, because Guyuk is in
        # both. It also drew the same event into several graphs. The causal chain across eras
        # is the timeline's job; this page answers who was here and what happened here.
        era_events = sorted({e for c in here for e in appears.get(c["id"], ())
                             if in_era(events[e], epoch["id"])})

        doc += [f"## {epoch['name']}", ""]
        if not here:
            doc += ["Canon records nobody in this era yet.", ""]
            continue

        # Faction first, then culture, so a claimed character lands in exactly one box.
        groups: dict[tuple[str, str], list[dict]] = collections.defaultdict(list)
        for c in sorted(here, key=lambda c: c["name"]):
            faction = claims.get(c["id"])
            if faction:
                groups[("faction", faction["name"])].append(c)
            else:
                groups[("culture", c.get("culture") or "no culture recorded")].append(c)

        lines = ["```mermaid", "graph LR"]
        for (kind, name), members in sorted(groups.items(), key=lambda kv: (kv[0][0], kv[0][1])):
            tag = name if kind == "faction" else f"{name} ({kind})"
            lines.append(f'  subgraph grp_{node_id(name.lower().replace(" ", "_"))}["{label(tag)}"]')
            for c in members:
                lines.append(f'    {node_id(c["id"])}("{label(c["name"])}")')
            lines.append("  end")
        for eid in era_events:
            title = events[eid].get("title") or eid
            lines.append(f'  {node_id(eid)}["{label(title)}"]')
        for c in sorted(here, key=lambda c: c["id"]):
            for eid in sorted(appears.get(c["id"], ())):
                if eid in era_events:
                    lines.append(f'  {node_id(c["id"])} --> {node_id(eid)}')
        lines.append("```")

        era_set = set(era_events)
        unplaced = [c["name"] for c in sorted(here, key=lambda c: c["name"])
                    if not (appears.get(c["id"], set()) & era_set)]
        doc += lines + [""]
        doc.append(f"{len(here)} character(s), {len(era_events)} event(s) they appear in, "
                   f"{len(groups)} group(s).")
        if unplaced:
            doc.append("")
            doc.append(f"**Present in no event of this era:** {', '.join(unplaced)}.")
        doc += [""]
        drawn += 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(doc), encoding="utf-8")
    print(f"✅ Memory map → {OUT_MD.relative_to(BASE)}")
    print(f"   {len(characters)} characters, {len(events)} events, {len(factions)} factions, "
          f"{drawn} era(s) drawn")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
