"""Publish the reference books: the bestiary and the cookbook.

**Two, since 2 October 2026.** There were four. The apothecary and the workshop were the making
layer seen as a book -- medicine, materials, objects, recipes -- and the owner moved making to the
game, so canon no longer holds what they were made from. The cookbook stays, built from the
customs alone: its reason for existing was always the `foodways`, which nothing else reads. A
custom names its dish by the game's item id, so the dish is printed as words, not as a link.

The timeline says *when*, the atlas says *where*, the memory map says *who*. These four say
**what** -- the 365 living things canon holds, the medicine made from them, the craft that turns
them into objects, and the food.

One script rather than four, which breaks the one-generator-per-artifact pattern the other
views follow. The reason is that these four are one query over one dataset seen from four
angles: every page loads the same folders, resolves the same cross-references and formats the
same entity rows. Four scripts would be four copies of that, and the copies would drift the way
`diarySections` and `Diary.tsx` drifted in the game before they were made one builder.

**Built the way a role-playing compendium is built**, because that is what these are and the
form is long settled. Three borrowings, all from Paizo's Archives of Nethys and the stat-block
conventions it publishes:

  1. **A traits line.** Pathfinder puts a row of keywords under every name -- rarity, then the
     tags that decide how a thing interacts with everything else -- and it doubles as the filter
     dimension. Canon already *had* traits and was printing them as prose: `rarity` on a species,
     `classes` on a material, `affords` on an item, `uses` on a plant. They are keywords now.
  2. **Entries link to each other.** A compendium is worth using because a monster's ability
     reaches its description and a feat reaches its prerequisite. So a recipe's ingredients are
     links to the materials, a material links to the species it is won from, and a dish links to
     the custom that eats it.
  3. **Backlinks, which are the half that makes it usable.** Knowing what a reed is matters less
     than knowing what is made *of* reed, and only one of those is written down anywhere. Every
     material entry ends with what uses it, gathered by walking the recipes backwards.

Table view for the bestiary and stat blocks for the made things, which is the same split the
Archives makes: 365 species is a thing you browse and filter, and a recipe is a thing you read.

**The cookbook is the reason this exists at all.** `foodways/` is deliberately not exported --
what a loaf means on the night the river comes over the bank is a fact about the Harappans and
belongs beside mythology, not in a browser bundle. Which left fifteen entities that nothing
whatsoever read: authored, linted, cross-referenced, and never once shown to anybody. The book
is their reader, and it always was; they were written before it existed.

    python utils/generate_books.py
"""

from __future__ import annotations

import collections
import json
import re
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

BASE = Path(__file__).resolve().parent.parent
DB = BASE / "database"
DOCS = BASE / "docs"

sys.path.insert(0, str(Path(__file__).resolve().parent))
from book_nav import PAGES, nav  # noqa: E402


def load(folder: str) -> list[dict]:
    d = DB / folder
    if not d.exists():
        return []
    out = [json.loads(f.read_text(encoding="utf-8")) for f in sorted(d.glob("*.json"))]
    # Same ordering the exporter uses, for the same reason: `source_index` is the authored
    # sequence and anything without one sorts after, by id. A book that listed things in
    # filesystem order would reshuffle whenever something was renamed.
    return sorted(out, key=lambda e: (e.get("source_index", 10**9), e.get("id", "")))


def vocab(filename: str, key: str) -> dict[str, dict]:
    p = DB / filename
    return json.loads(p.read_text(encoding="utf-8"))[key] if p.exists() else {}


def page(filename: str, title: str, blurb: str, body: list[str]) -> None:
    """Write one book, in the shape the other generated pages already have."""
    lines = [
        f"# {title}",
        "",
        nav(filename),
        "",
        "*Generated by `utils/generate_books.py`. Do not edit by hand.*",
        "",
        blurb,
        "",
        *body,
        "",
    ]
    (DOCS / filename).write_text("\n".join(lines), encoding="utf-8")
    print(f"  {filename:18} {len(lines)} lines")


def named(entities: list[dict]) -> dict[str, dict]:
    return {e["id"]: e for e in entities}


# Every id in canon, resolved to the name a reader would use and the page it is written on.
#
# A book that prints `2 × material_delta_rice` is a database dump with headings; one that prints
# `2 × Red delta rice` and does not let you reach it is a catalogue. The ids are canon's business
# and the point of a generated book is that it is neither of those.
#
# `id -> (name, page or None)`. A page of None means the thing has a name but no entry to reach,
# which is true of species in the table view and of anything a book does not cover.
NAMES: dict[str, str] = {}
ENTRY_PAGE: dict[str, str] = {}

SITE = "https://lordlebu.github.io/SouthOfTethys"


def slug(text: str) -> str:
    """A heading anchor, the way both render targets build one.

    GitHub and kramdown both derive a heading's id from its text: lowercase, punctuation
    dropped, spaces to hyphens. They agree for every name canon has, and relying on that is
    what lets one link work in the repository and on the site -- the same two-target problem
    `book_nav.py` solves with absolute URLs, one level down.
    """
    keep = [c.lower() if c.isalnum() else ("-" if c in " _-" else "") for c in text]
    return "".join(keep).strip("-")


def readable(ref: str | None) -> str:
    """An id, a `#class` tag or a bare string, as something a person would say."""
    if not ref:
        return ""
    if ref.startswith("#"):
        return ref[1:]
    return NAMES.get(ref, ref)


def link(ref: str | None, page: str | None = None) -> str:
    """A cross-reference, as a link where there is an entry to reach and prose where there is not.

    Within a page the anchor alone is enough. Across pages it has to be the published absolute
    URL: a relative `workshop.html` 404s in the repository and a relative `workshop.md` 404s on
    the site, which is the reason `book_nav.py` gives for doing the same thing.
    """
    if not ref:
        return ""
    name = readable(ref)
    if ref.startswith("#"):
        return f"`{name}`"
    where = ENTRY_PAGE.get(ref)
    if not where:
        return name
    anchor = f"#{slug(name)}"
    return f"[{name}]({anchor})" if where == page else f"[{name}]({SITE}/{where}.html{anchor})"


def traits(*groups: object) -> str:
    """A Pathfinder-style keyword line: rarity first, then the tags, comma separated.

    Presentation only -- every keyword here is already a value in a declared vocabulary, and
    that is the point. A trait line a reader can scan and a lint that refuses the twenty-second
    value typed by accident are the same list seen from two ends.
    """
    words: list[str] = []
    for g in groups:
        if not g:
            continue
        words.extend([g] if isinstance(g, str) else list(g))
    seen = list(dict.fromkeys(w for w in words if w))
    return "*" + " · ".join(seen) + "*" if seen else ""


def takes(recipe: dict, page: str | None = None) -> str:
    """A recipe's ingredients, as links where there is somewhere to go."""
    parts = []
    for n in recipe.get("ingredients") or []:
        what = link(n.get("tag") or n.get("material") or n.get("item"), page)
        count = n.get("count", 1)
        kept = " *(kept)*" if n.get("kept") else ""
        parts.append(f"{count} × {what}{kept}" if count > 1 else f"{what}{kept}")
    return ", ".join(parts)


def gives(recipe: dict, page: str | None = None) -> str:
    """A recipe's outputs, as links where there is somewhere to go."""
    parts = []
    for o in recipe.get("outputs") or []:
        what = link(o.get("item") or o.get("material"), page)
        count = o.get("count", 1)
        parts.append(f"{count} × {what}" if count > 1 else what)
    return ", ".join(parts)


def also_known(e: dict) -> str:
    """A plant or animal's other names, and its binomial.

    Printed because a reference nobody can search is a reference nobody uses. Canon names
    kuchla `Kuchla`, which is right for a world whose people would not say *Strychnos* -- and
    it meant a reader who came looking for nux-vomica found an empty page in a book that had
    the plant in it twice.
    """
    names = list(e.get("aliases") or [])
    if e.get("scientific"):
        names.append(f"*{e['scientific']}*")
    return " · ".join(names)


def sentence(text: str | None) -> str:
    """Canon's prose, trimmed to its first sentence for an index entry."""
    if not text:
        return ""
    first = text.replace("\n", " ").split(". ")[0].strip()
    return first if first.endswith(".") else f"{first}."


# --------------------------------------------------------------------------- the bestiary


def bestiary(fauna: list[dict], flora: list[dict], regions: list[dict]) -> None:
    clades = vocab("clades.json", "clades")
    forms = vocab("growth_forms.json", "forms")
    forms = forms if isinstance(forms, dict) else {f: {} for f in forms}
    region_name = {r.get("bestiary_region", r["id"]): r["name"] for r in regions}

    body: list[str] = [
        f"Canon holds **{len(fauna)} animals and {len(flora)} plants**. They are grouped here by "
        "the region they were recorded in, because that is how the bestiary they came from was "
        "organised and because a reader looking one up is usually looking at a place.",
        "",
        "A species that can be met in play carries its biomes; one marked *lore* is written "
        "about and never placed, which is most of the sky and all of the Asura conjurations.",
        "",
    ]

    by_region: dict[str, list[dict]] = collections.defaultdict(list)
    for e in fauna + flora:
        by_region[e.get("region") or "canon"].append(e)

    for region in sorted(by_region, key=lambda r: (-len(by_region[r]), r)):
        here = by_region[region]
        body.append(f"## {region_name.get(region, region.replace('-', ' ').title())}")
        body.append("")
        body.append(f"*{len(here)} recorded.*")
        body.append("")
        body.append("| Species | Traits | What it is |")
        body.append("|---|---|---|")
        for e in sorted(here, key=lambda x: x["name"]):
            kind = e.get("clade") or e.get("growth_form") or ""
            gloss = (clades.get(kind) or forms.get(kind) or {})
            gloss = gloss.get("label", kind) if isinstance(gloss, dict) else kind
            other = also_known(e)
            sci = f"<br>{other}" if other else ""
            # Rarity first, then what it is, then where -- and `lore only` where canon writes
            # about something it never places, which is the trait a reader most needs and the
            # old table buried in a parenthesis at the end of a column.
            tags = [e.get("rarity", ""), gloss]
            if e.get("placement") == "lore":
                tags.append("lore only")
            tags.extend(e.get("biomes") or [])
            tags.extend(e.get("uses") or [])
            body.append(f"| **{e['name']}**{sci} | {traits(tags)} | {sentence(e.get('journal_prompt'))} |")
        body.append("")

    page(
        "bestiary.md",
        "The Bestiary",
        "Every living thing canon records, and where it was recorded.",
        body,
    )


# --------------------------------------------------------------------------- the apothecary


def cookbook(foodways: list[dict]) -> None:
    by_dish: dict[str, list[dict]] = collections.defaultdict(list)
    for f in foodways:
        by_dish[f.get("dish", "")].append(f)

    body: list[str] = [
        f"**{len(foodways)} customs, around {len(by_dish)} dishes.** What this world eats, and -- "
        "the part that matters -- when and why.",
        "",
        "**The customs are the reason this page exists.** A `foodway` is deliberately not "
        "exported to the game: what a loaf *means* on the night the river comes over the bank is "
        "a fact about a people and belongs beside mythology. The dishes themselves are the "
        "game's to cook, and live there.",
        "",
        "## What is eaten, and what it is for",
        "",
    ]
    for dish in sorted(by_dish, key=readable):
        body.append(f"### {readable(dish).capitalize()}")
        body.append("")
        for f in by_dish[dish]:
            body.append(f"> **{f['name']}** *({f.get('culture','')})* -- {f.get('occasion','')}")
            body.append(">")
            for para in (f.get("meaning") or "").split("\n\n"):
                body.append(f"> {para.strip()}")
                body.append(">")
            body.pop()
            body.append("")

    page("cookbook.md", "The Cookbook",
         "What is eaten, when it is eaten, and what eating it says.", body)


def check_links() -> list[str]:
    """Every internal link in the books points at a heading that exists.

    A compendium whose cross-references go nowhere is worse than one with none: it invites the
    reader to follow something and then wastes the click. These links are all generated, so the
    only way one breaks is a heading changing shape -- which is exactly the kind of thing nobody
    notices in a 1,300-line generated page, and exactly what a generator should check about its
    own output.

    Compared as slugs rather than as text, because a slug is what both render targets resolve.
    """
    heading = re.compile(r"^#{2,4} (.+)$", re.M)
    ref = re.compile(r"\]\((?:" + re.escape(SITE) + r"/(\w+)\.html)?#([\w-]+)\)")

    have: dict[str, set[str]] = {}
    want: list[tuple[str, str, str]] = []
    for path in sorted(DOCS.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        have[path.stem] = {slug(m) for m in heading.findall(text)}
        for page, anchor in ref.findall(text):
            want.append((path.stem, page or path.stem, anchor))

    broken = [
        f"{page}.md links to {dest}#{anchor}, which is not a heading there"
        for page, dest, anchor in want
        if dest in have and anchor not in have[dest]
    ]

    # And every published page carries the whole nav.
    #
    # This is the failure `book_nav.py` was written to prevent, and adding four books to `PAGES`
    # reintroduced it inside a day: the nav is shared state across five generators, so a new page
    # is only linked from the pages that happen to be regenerated afterwards. Four books shipped
    # reachable and linked from nowhere but each other, exactly as the atlas and timeline once
    # were, and nothing failed -- because from inside the repository it looks done.
    #
    # Checked here rather than in `book_nav.py` because only a thing that reads `docs/` can see
    # it, and this generator already reads all of `docs/`.
    for filename, _page, label in PAGES:
        path = DOCS / filename
        if not path.exists():
            broken.append(f"{filename} is in book_nav.PAGES and does not exist")
            continue
        text = path.read_text(encoding="utf-8")
        for _other, _p, other_label in PAGES:
            # Against the escaped label, because that is what `nav` writes: "Epochs & Events"
            # reaches the page as "Epochs &amp; Events" and searching for the raw ampersand
            # reports every page as broken, which is how this check first read.
            if other_label.replace("&", "&amp;") not in text:
                broken.append(
                    f"{filename} does not link to {other_label!r} -- its nav is stale, so "
                    f"re-run every generator rather than only the one you changed"
                )
    return broken


def main() -> int:
    fauna, flora = load("fauna"), load("flora")
    foodways = load("foodways")

    for group in (fauna, flora, load("npcs")):
        for e in group:
            NAMES[e["id"]] = e.get("name", e["id"])

    bestiary(fauna, flora, load("regions"))
    cookbook(foodways)
    broken = check_links()
    for b in broken:
        print(f"  BROKEN  {b}")
    print(f"\nTwo books from {len(fauna) + len(flora)} species and {len(foodways)} customs.")
    if broken:
        print(f"{len(broken)} cross-reference(s) point at nothing.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
