"""Publish the four reference books: bestiary, apothecary, workshop, cookbook.

The timeline says *when*, the atlas says *where*, the memory map says *who*. These four say
**what** -- the 365 living things canon holds, the medicine made from them, the craft that turns
them into objects, and the food.

One script rather than four, which breaks the one-generator-per-artifact pattern the other
views follow. The reason is that these four are one query over one dataset seen from four
angles: every page loads the same folders, resolves the same cross-references and formats the
same entity rows. Four scripts would be four copies of that, and the copies would drift the way
`diarySections` and `Diary.tsx` drifted in the game before they were made one builder.

**The cookbook is the reason this exists at all.** `foodways/` is deliberately not exported --
what a loaf means on the night the river comes over the bank is a fact about the Harappans and
belongs beside mythology, not in a browser bundle. Which left fifteen entities that nothing
whatsoever read: authored, linted, cross-referenced, and never once shown to anybody. The book
is their reader, and it always was; they were written before it existed.

    python utils/generate_books.py
"""

from __future__ import annotations

import collections
import json
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

BASE = Path(__file__).resolve().parent.parent
DB = BASE / "database"
DOCS = BASE / "docs"

sys.path.insert(0, str(Path(__file__).resolve().parent))
from book_nav import nav  # noqa: E402


def load(folder: str) -> list[dict]:
    d = DB / folder
    if not d.exists():
        return []
    out = [json.loads(f.read_text(encoding="utf-8")) for f in sorted(d.glob("*.json"))]
    # Same ordering the exporter uses, for the same reason: `source_index` is the authored
    # sequence and anything without one sorts after, by id. A book that listed things in
    # filesystem order would reshuffle whenever something was renamed.
    return sorted(out, key=lambda e: (e.get("source_index", 10**9), e.get("id", "")))


def vocab(filename: str, key: str) -> dict[str, dict]:
    p = DB / filename
    return json.loads(p.read_text(encoding="utf-8"))[key] if p.exists() else {}


def page(filename: str, title: str, blurb: str, body: list[str]) -> None:
    """Write one book, in the shape the other generated pages already have."""
    lines = [
        f"# {title}",
        "",
        nav(filename),
        "",
        "*Generated by `utils/generate_books.py`. Do not edit by hand.*",
        "",
        blurb,
        "",
        *body,
        "",
    ]
    (DOCS / filename).write_text("\n".join(lines), encoding="utf-8")
    print(f"  {filename:18} {len(lines)} lines")


def named(entities: list[dict]) -> dict[str, dict]:
    return {e["id"]: e for e in entities}


# Every id in canon resolved to the name a reader would use, filled in by `main`.
#
# A book that prints `2 × material_delta_rice` is a database dump with headings. The ids are
# canon's business and the whole point of a generated book is that it is not.
NAMES: dict[str, str] = {}


def readable(ref: str | None) -> str:
    """An id, a `#class` tag or a bare string, as something a person would say."""
    if not ref:
        return ""
    if ref.startswith("#"):
        return ref[1:]
    return NAMES.get(ref, ref)


def takes(recipe: dict) -> str:
    """A recipe's ingredients, in words."""
    parts = []
    for n in recipe.get("ingredients") or []:
        what = readable(n.get("tag") or n.get("material") or n.get("item"))
        count = n.get("count", 1)
        kept = " *(kept)*" if n.get("kept") else ""
        parts.append(f"{count} × {what}{kept}" if count > 1 else f"{what}{kept}")
    return ", ".join(parts)


def gives(recipe: dict) -> str:
    """A recipe's outputs, in words."""
    parts = []
    for o in recipe.get("outputs") or []:
        what = readable(o.get("item") or o.get("material"))
        count = o.get("count", 1)
        parts.append(f"{count} × {what}" if count > 1 else what)
    return ", ".join(parts)


def sentence(text: str | None) -> str:
    """Canon's prose, trimmed to its first sentence for an index entry."""
    if not text:
        return ""
    first = text.replace("\n", " ").split(". ")[0].strip()
    return first if first.endswith(".") else f"{first}."


# --------------------------------------------------------------------------- the bestiary


def bestiary(fauna: list[dict], flora: list[dict], regions: list[dict]) -> None:
    clades = vocab("clades.json", "clades")
    forms = vocab("growth_forms.json", "forms")
    forms = forms if isinstance(forms, dict) else {f: {} for f in forms}
    region_name = {r.get("bestiary_region", r["id"]): r["name"] for r in regions}

    body: list[str] = [
        f"Canon holds **{len(fauna)} animals and {len(flora)} plants**. They are grouped here by "
        "the region they were recorded in, because that is how the bestiary they came from was "
        "organised and because a reader looking one up is usually looking at a place.",
        "",
        "A species that can be met in play carries its biomes; one marked *lore* is written "
        "about and never placed, which is most of the sky and all of the Asura conjurations.",
        "",
    ]

    by_region: dict[str, list[dict]] = collections.defaultdict(list)
    for e in fauna + flora:
        by_region[e.get("region") or "canon"].append(e)

    for region in sorted(by_region, key=lambda r: (-len(by_region[r]), r)):
        here = by_region[region]
        body.append(f"## {region_name.get(region, region.replace('-', ' ').title())}")
        body.append("")
        body.append(f"*{len(here)} recorded.*")
        body.append("")
        body.append("| | Species | What it is | Where |")
        body.append("|---|---|---|---|")
        for e in sorted(here, key=lambda x: x["name"]):
            kind = e.get("clade") or e.get("growth_form") or ""
            gloss = (clades.get(kind) or forms.get(kind) or {})
            gloss = gloss.get("label", kind) if isinstance(gloss, dict) else kind
            sci = f"*{e['scientific']}*" if e.get("scientific") else ""
            where = ", ".join(e.get("biomes") or []) or "—"
            if e.get("placement") == "lore":
                where = f"{where} (lore only)"
            body.append(f"| {gloss} | **{e['name']}** {sci} | {sentence(e.get('journal_prompt'))} | {where} |")
        body.append("")

    page(
        "bestiary.md",
        "The Bestiary",
        "Every living thing canon records, and where it was recorded.",
        body,
    )


# --------------------------------------------------------------------------- the apothecary


def apothecary(flora: list[dict], materials: list[dict], items: list[dict], recipes: list[dict]) -> None:
    healing_plants = [f for f in flora if "physic" in (f.get("uses") or [])]
    poisons = [f for f in flora if "poison" in (f.get("uses") or [])]
    minds = [f for f in flora if "psychoactive" in (f.get("uses") or [])]
    stuff = [m for m in materials if "physic" in (m.get("classes") or [])]
    made = [i for i in items if i.get("kind") == "physic" or "heal" in (i.get("affords") or [])]
    made_ids = {i["id"] for i in made}
    how = [r for r in recipes if any(o.get("item") in made_ids for o in r.get("outputs") or [])]

    body: list[str] = [
        "What this world treats a hurt with, and what it is careful of. Canon has no healing "
        "*mechanic* -- nothing here restores anything to anybody, and the game reads `heal` as "
        "description rather than as a number. What it has is a pharmacopoeia: bitter barks, "
        "scraped resins and one mineral exudate, mostly bitter and mostly taken because "
        "somebody once found out the hard way.",
        "",
    ]

    def table(rows: list[dict], heading: str, note: str, describe) -> None:
        if not rows:
            return
        body.extend([f"## {heading}", "", note, "", "| Name | Notes |", "|---|---|"])
        for e in sorted(rows, key=lambda x: x["name"]):
            body.append(f"| **{e['name']}** | {describe(e)} |")
        body.append("")

    table(healing_plants, "Plants taken as physic",
          f"{len(healing_plants)} of canon's plants are recorded as medicine.",
          lambda e: sentence(e.get("notes")))
    table(stuff, "What is carried",
          "The substances themselves, once gathered.",
          lambda e: sentence(e.get("notes")))
    table(made, "What is prepared",
          "Salve, poultice and tonic -- three preparations and nothing more elaborate.",
          lambda e: sentence(e.get("notes")))
    table(minds, "Plants that change the mind",
          "Kept apart from physic, deliberately: a dream-inducer is not a treatment, and filing "
          "it as one would have canon claiming something it does not.",
          lambda e: sentence(e.get("notes")))
    table(poisons, "Plants known to harm",
          "Their own category rather than a negative. A culture that plants oleander on a "
          "boundary is using the harm on purpose.",
          lambda e: sentence(e.get("notes")))

    if how:
        body.extend(["## How they are made", "", "| Preparation | Takes |", "|---|---|"])
        for r in sorted(how, key=lambda x: x["name"]):
            body.append(f"| **{r['name']}** | {takes(r)} |")
        body.append("")

    page("apothecary.md", "The Apothecary",
         "Bitter barks, scraped resins, and the things it is wiser not to eat.", body)


# --------------------------------------------------------------------------- the workshop


def workshop(materials, items, processes, recipes, vehicles) -> None:
    classes = vocab("material_classes.json", "classes")
    affordances = vocab("affordances.json", "affordances")
    proc_by_id = named(processes)
    prototypes = {i["base_item"] for i in items if i.get("base_item")}

    body: list[str] = [
        f"**{len(materials)} materials, {len(items)} objects, {len(processes)} ways of making "
        f"and {len(recipes)} recipes.** Everything canon knows about turning one thing into "
        "another.",
        "",
        "A recipe names a `#class` wherever any material of that kind will do, which is why "
        "there are seventy-odd of them rather than one per species. An item marked *prototype* "
        "exists to be inherited from and is never made on its own.",
        "",
        "## Materials, by what they are",
        "",
    ]

    by_class: dict[str, list[dict]] = collections.defaultdict(list)
    for m in materials:
        for c in m.get("classes") or []:
            by_class[c].append(m)
    for c, gloss in classes.items():
        here = by_class.get(c) or []
        if not here:
            continue
        label = gloss.get("label", c) if isinstance(gloss, dict) else c
        names = ", ".join(sorted(m["name"] for m in here))
        body.append(f"- **{label}** (`#{c}`) — {names}")
    body.append("")

    body.extend(["## Ways of making", "", "| Process | Done at | Needs | |", "|---|---|---|---|"])
    for p in processes:
        at = ", ".join(p.get("performed_at") or []) or "anywhere"
        needs = ", ".join(
            (affordances.get(n) or {}).get("label", n) if isinstance(affordances.get(n), dict) else n
            for n in p.get("needs") or []
        ) or "nothing"
        body.append(f"| **{p['name']}** | {at} | {needs} | {sentence(p.get('notes'))} |")
    body.append("")

    body.extend(["## Recipes, by how they are done", ""])
    by_proc: dict[str, list[dict]] = collections.defaultdict(list)
    for r in recipes:
        by_proc[r.get("process", "")].append(r)
    for pid, here in sorted(by_proc.items(), key=lambda kv: proc_by_id.get(kv[0], {}).get("source_index", 0)):
        body.append(f"### {proc_by_id.get(pid, {}).get('name', pid)}")
        body.append("")
        body.append("| Makes | From | Taught by |")
        body.append("|---|---|---|")
        for r in sorted(here, key=lambda x: x["name"]):
            taught = ", ".join(readable(w) for w in r.get("taught_by") or []) or "common knowledge"
            body.append(f"| {gives(r)} | {takes(r)} | {taught} |")
        body.append("")

    body.extend(["## Objects, by what they are for", "", "| Kind | Object | Affords | |", "|---|---|---|---|"])
    for i in sorted(items, key=lambda x: (x.get("kind", ""), x["name"])):
        aff = ", ".join(i.get("affords") or [])
        proto = " *(prototype)*" if i["id"] in prototypes else ""
        body.append(f"| {i.get('kind','')} | **{i['name']}**{proto} | {aff} | {sentence(i.get('notes'))} |")
    body.append("")

    if vehicles:
        body.extend(["## Things that carry you", "", "| Craft | Kind | Crosses | Carries | |", "|---|---|---|---|---|"])
        for v in vehicles:
            body.append(
                f"| **{v['name']}** | {v.get('kind','')} | {', '.join(v.get('crosses') or [])} | "
                f"{v.get('capacity','—')} | {sentence(v.get('notes'))} |"
            )
        body.append("")

    page("workshop.md", "The Workshop",
         "What things are made of, and how they are made.", body)


# --------------------------------------------------------------------------- the cookbook


def cookbook(items, recipes, foodways, materials) -> None:
    food = [i for i in items if "eat" in (i.get("affords") or [])]
    food_ids = {i["id"] for i in food}
    dishes = [r for r in recipes if any(o.get("item") in food_ids for o in r.get("outputs") or [])]
    edible = [m for m in materials if set(m.get("classes") or []) & {"produce", "grain", "flesh", "spice", "salt", "oil"}]
    by_dish: dict[str, list[dict]] = collections.defaultdict(list)
    for f in foodways:
        by_dish[f.get("dish", "")].append(f)
    item_name = {i["id"]: i["name"] for i in items}

    body: list[str] = [
        f"**{len(food)} dishes, {len(dishes)} recipes and {len(foodways)} customs.** What this "
        "world eats, and — the part that matters — when and why.",
        "",
        "**The customs are the reason this page exists.** A `foodway` is deliberately not "
        "exported to the game: a dish is an object and ships, but what a loaf *means* on the "
        "night the river comes over the bank is a fact about a people and belongs beside "
        "mythology. That left them read by nothing at all. Here they are read.",
        "",
        "## What is eaten, and what it is for",
        "",
    ]

    for i in sorted(food, key=lambda x: x["name"]):
        body.append(f"### {i['name']}")
        body.append("")
        if i.get("notes"):
            body.append(i["notes"])
            body.append("")
        made_by = [r for r in dishes if any(o.get("item") == i["id"] for o in r.get("outputs") or [])]
        for r in made_by:
            body.append(f"**{r['name']}** — {takes(r)}.")
            body.append("")
        for f in by_dish.get(i["id"]) or []:
            body.append(f"> **{f['name']}** *({f.get('culture','')})* — {f.get('occasion','')}")
            body.append(">")
            for para in (f.get("meaning") or "").split("\n\n"):
                body.append(f"> {para.strip()}")
                body.append(">")
            body.pop()
            body.append("")

    if edible:
        body.extend(["## What it is made from", "", "| Ingredient | | |", "|---|---|---|"])
        for m in sorted(edible, key=lambda x: x["name"]):
            body.append(f"| **{m['name']}** | {', '.join(m.get('classes') or [])} | {sentence(m.get('notes'))} |")
        body.append("")

    page("cookbook.md", "The Cookbook",
         "What is eaten, when it is eaten, and what eating it says.", body)


def main() -> int:
    fauna, flora = load("fauna"), load("flora")
    materials, items = load("materials"), load("items")
    processes, recipes = load("processes"), load("recipes")
    vehicles, foodways = load("vehicles"), load("foodways")

    for group in (fauna, flora, materials, items, processes, recipes, vehicles, load("npcs")):
        for e in group:
            NAMES[e["id"]] = e.get("name", e["id"])

    bestiary(fauna, flora, load("regions"))
    apothecary(flora, materials, items, recipes)
    workshop(materials, items, processes, recipes, vehicles)
    cookbook(items, recipes, foodways, materials)
    print(f"\nFour books from {len(fauna) + len(flora)} species and "
          f"{len(materials) + len(items) + len(recipes)} made things.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
