"""Publish the four reference books: bestiary, apothecary, workshop, cookbook.

The timeline says *when*, the atlas says *where*, the memory map says *who*. These four say
**what** -- the 365 living things canon holds, the medicine made from them, the craft that turns
them into objects, and the food.

One script rather than four, which breaks the one-generator-per-artifact pattern the other
views follow. The reason is that these four are one query over one dataset seen from four
angles: every page loads the same folders, resolves the same cross-references and formats the
same entity rows. Four scripts would be four copies of that, and the copies would drift the way
`diarySections` and `Diary.tsx` drifted in the game before they were made one builder.

**Built the way a role-playing compendium is built**, because that is what these are and the
form is long settled. Three borrowings, all from Paizo's Archives of Nethys and the stat-block
conventions it publishes:

  1. **A traits line.** Pathfinder puts a row of keywords under every name -- rarity, then the
     tags that decide how a thing interacts with everything else -- and it doubles as the filter
     dimension. Canon already *had* traits and was printing them as prose: `rarity` on a species,
     `classes` on a material, `affords` on an item, `uses` on a plant. They are keywords now.
  2. **Entries link to each other.** A compendium is worth using because a monster's ability
     reaches its description and a feat reaches its prerequisite. So a recipe's ingredients are
     links to the materials, a material links to the species it is won from, and a dish links to
     the custom that eats it.
  3. **Backlinks, which are the half that makes it usable.** Knowing what a reed is matters less
     than knowing what is made *of* reed, and only one of those is written down anywhere. Every
     material entry ends with what uses it, gathered by walking the recipes backwards.

Table view for the bestiary and stat blocks for the made things, which is the same split the
Archives makes: 365 species is a thing you browse and filter, and a recipe is a thing you read.

**The cookbook is the reason this exists at all.** `foodways/` is deliberately not exported --
what a loaf means on the night the river comes over the bank is a fact about the Harappans and
belongs beside mythology, not in a browser bundle. Which left fifteen entities that nothing
whatsoever read: authored, linted, cross-referenced, and never once shown to anybody. The book
is their reader, and it always was; they were written before it existed.

    python utils/generate_books.py
"""

from __future__ import annotations

import collections
import json
import re
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

BASE = Path(__file__).resolve().parent.parent
DB = BASE / "database"
DOCS = BASE / "docs"

sys.path.insert(0, str(Path(__file__).resolve().parent))
from book_nav import PAGES, nav  # noqa: E402


def load(folder: str) -> list[dict]:
    d = DB / folder
    if not d.exists():
        return []
    out = [json.loads(f.read_text(encoding="utf-8")) for f in sorted(d.glob("*.json"))]
    # Same ordering the exporter uses, for the same reason: `source_index` is the authored
    # sequence and anything without one sorts after, by id. A book that listed things in
    # filesystem order would reshuffle whenever something was renamed.
    return sorted(out, key=lambda e: (e.get("source_index", 10**9), e.get("id", "")))


def vocab(filename: str, key: str) -> dict[str, dict]:
    p = DB / filename
    return json.loads(p.read_text(encoding="utf-8"))[key] if p.exists() else {}


def page(filename: str, title: str, blurb: str, body: list[str]) -> None:
    """Write one book, in the shape the other generated pages already have."""
    lines = [
        f"# {title}",
        "",
        nav(filename),
        "",
        "*Generated by `utils/generate_books.py`. Do not edit by hand.*",
        "",
        blurb,
        "",
        *body,
        "",
    ]
    (DOCS / filename).write_text("\n".join(lines), encoding="utf-8")
    print(f"  {filename:18} {len(lines)} lines")


def named(entities: list[dict]) -> dict[str, dict]:
    return {e["id"]: e for e in entities}


# Every id in canon, resolved to the name a reader would use and the page it is written on.
#
# A book that prints `2 × material_delta_rice` is a database dump with headings; one that prints
# `2 × Red delta rice` and does not let you reach it is a catalogue. The ids are canon's business
# and the point of a generated book is that it is neither of those.
#
# `id -> (name, page or None)`. A page of None means the thing has a name but no entry to reach,
# which is true of species in the table view and of anything a book does not cover.
NAMES: dict[str, str] = {}
ENTRY_PAGE: dict[str, str] = {}

SITE = "https://lordlebu.github.io/SouthOfTethys"


def slug(text: str) -> str:
    """A heading anchor, the way both render targets build one.

    GitHub and kramdown both derive a heading's id from its text: lowercase, punctuation
    dropped, spaces to hyphens. They agree for every name canon has, and relying on that is
    what lets one link work in the repository and on the site -- the same two-target problem
    `book_nav.py` solves with absolute URLs, one level down.
    """
    keep = [c.lower() if c.isalnum() else ("-" if c in " _-" else "") for c in text]
    return "".join(keep).strip("-")


def readable(ref: str | None) -> str:
    """An id, a `#class` tag or a bare string, as something a person would say."""
    if not ref:
        return ""
    if ref.startswith("#"):
        return ref[1:]
    return NAMES.get(ref, ref)


def link(ref: str | None, page: str | None = None) -> str:
    """A cross-reference, as a link where there is an entry to reach and prose where there is not.

    Within a page the anchor alone is enough. Across pages it has to be the published absolute
    URL: a relative `workshop.html` 404s in the repository and a relative `workshop.md` 404s on
    the site, which is the reason `book_nav.py` gives for doing the same thing.
    """
    if not ref:
        return ""
    name = readable(ref)
    if ref.startswith("#"):
        return f"`{name}`"
    where = ENTRY_PAGE.get(ref)
    if not where:
        return name
    anchor = f"#{slug(name)}"
    return f"[{name}]({anchor})" if where == page else f"[{name}]({SITE}/{where}.html{anchor})"


def traits(*groups: object) -> str:
    """A Pathfinder-style keyword line: rarity first, then the tags, comma separated.

    Presentation only -- every keyword here is already a value in a declared vocabulary, and
    that is the point. A trait line a reader can scan and a lint that refuses the twenty-second
    value typed by accident are the same list seen from two ends.
    """
    words: list[str] = []
    for g in groups:
        if not g:
            continue
        words.extend([g] if isinstance(g, str) else list(g))
    seen = list(dict.fromkeys(w for w in words if w))
    return "*" + " · ".join(seen) + "*" if seen else ""


def takes(recipe: dict, page: str | None = None) -> str:
    """A recipe's ingredients, as links where there is somewhere to go."""
    parts = []
    for n in recipe.get("ingredients") or []:
        what = link(n.get("tag") or n.get("material") or n.get("item"), page)
        count = n.get("count", 1)
        kept = " *(kept)*" if n.get("kept") else ""
        parts.append(f"{count} × {what}{kept}" if count > 1 else f"{what}{kept}")
    return ", ".join(parts)


def gives(recipe: dict, page: str | None = None) -> str:
    """A recipe's outputs, as links where there is somewhere to go."""
    parts = []
    for o in recipe.get("outputs") or []:
        what = link(o.get("item") or o.get("material"), page)
        count = o.get("count", 1)
        parts.append(f"{count} × {what}" if count > 1 else what)
    return ", ".join(parts)


def sentence(text: str | None) -> str:
    """Canon's prose, trimmed to its first sentence for an index entry."""
    if not text:
        return ""
    first = text.replace("\n", " ").split(". ")[0].strip()
    return first if first.endswith(".") else f"{first}."


# --------------------------------------------------------------------------- the bestiary


def bestiary(fauna: list[dict], flora: list[dict], regions: list[dict]) -> None:
    clades = vocab("clades.json", "clades")
    forms = vocab("growth_forms.json", "forms")
    forms = forms if isinstance(forms, dict) else {f: {} for f in forms}
    region_name = {r.get("bestiary_region", r["id"]): r["name"] for r in regions}

    body: list[str] = [
        f"Canon holds **{len(fauna)} animals and {len(flora)} plants**. They are grouped here by "
        "the region they were recorded in, because that is how the bestiary they came from was "
        "organised and because a reader looking one up is usually looking at a place.",
        "",
        "A species that can be met in play carries its biomes; one marked *lore* is written "
        "about and never placed, which is most of the sky and all of the Asura conjurations.",
        "",
    ]

    by_region: dict[str, list[dict]] = collections.defaultdict(list)
    for e in fauna + flora:
        by_region[e.get("region") or "canon"].append(e)

    for region in sorted(by_region, key=lambda r: (-len(by_region[r]), r)):
        here = by_region[region]
        body.append(f"## {region_name.get(region, region.replace('-', ' ').title())}")
        body.append("")
        body.append(f"*{len(here)} recorded.*")
        body.append("")
        body.append("| Species | Traits | What it is |")
        body.append("|---|---|---|")
        for e in sorted(here, key=lambda x: x["name"]):
            kind = e.get("clade") or e.get("growth_form") or ""
            gloss = (clades.get(kind) or forms.get(kind) or {})
            gloss = gloss.get("label", kind) if isinstance(gloss, dict) else kind
            sci = f"<br>*{e['scientific']}*" if e.get("scientific") else ""
            # Rarity first, then what it is, then where -- and `lore only` where canon writes
            # about something it never places, which is the trait a reader most needs and the
            # old table buried in a parenthesis at the end of a column.
            tags = [e.get("rarity", ""), gloss]
            if e.get("placement") == "lore":
                tags.append("lore only")
            tags.extend(e.get("biomes") or [])
            tags.extend(e.get("uses") or [])
            body.append(f"| **{e['name']}**{sci} | {traits(tags)} | {sentence(e.get('journal_prompt'))} |")
        body.append("")

    page(
        "bestiary.md",
        "The Bestiary",
        "Every living thing canon records, and where it was recorded.",
        body,
    )


# --------------------------------------------------------------------------- the apothecary


def apothecary(flora: list[dict], materials: list[dict], items: list[dict], recipes: list[dict]) -> None:
    healing_plants = [f for f in flora if "physic" in (f.get("uses") or [])]
    poisons = [f for f in flora if "poison" in (f.get("uses") or [])]
    minds = [f for f in flora if "psychoactive" in (f.get("uses") or [])]
    stuff = [m for m in materials if "physic" in (m.get("classes") or [])]
    made = [i for i in items if i.get("kind") == "physic" or "heal" in (i.get("affords") or [])]
    made_ids = {i["id"] for i in made}
    how = [r for r in recipes if any(o.get("item") in made_ids for o in r.get("outputs") or [])]

    body: list[str] = [
        "What this world treats a hurt with, and what it is careful of. Canon has no healing "
        "*mechanic* -- nothing here restores anything to anybody, and the game reads `heal` as "
        "description rather than as a number. What it has is a pharmacopoeia: bitter barks, "
        "scraped resins and one mineral exudate, mostly bitter and mostly taken because "
        "somebody once found out the hard way.",
        "",
    ]

    def table(rows: list[dict], heading: str, note: str, describe) -> None:
        if not rows:
            return
        body.extend([f"## {heading}", "", note, "", "| Name | Notes |", "|---|---|"])
        for e in sorted(rows, key=lambda x: x["name"]):
            body.append(f"| **{e['name']}** | {describe(e)} |")
        body.append("")

    table(healing_plants, "Plants taken as physic",
          f"{len(healing_plants)} of canon's plants are recorded as medicine.",
          lambda e: sentence(e.get("notes")))
    table(stuff, "What is carried",
          "The substances themselves, once gathered.",
          lambda e: sentence(e.get("notes")))
    table(made, "What is prepared",
          "Salve, poultice and tonic -- three preparations and nothing more elaborate.",
          lambda e: sentence(e.get("notes")))
    table(minds, "Plants that change the mind",
          "Kept apart from physic, deliberately: a dream-inducer is not a treatment, and filing "
          "it as one would have canon claiming something it does not.",
          lambda e: sentence(e.get("notes")))
    table(poisons, "Plants known to harm",
          "Their own category rather than a negative. A culture that plants oleander on a "
          "boundary is using the harm on purpose.",
          lambda e: sentence(e.get("notes")))

    if how:
        body.extend(["## How they are made", "", "| Preparation | Takes |", "|---|---|"])
        for r in sorted(how, key=lambda x: x["name"]):
            body.append(f"| {link(r['id'])} | {takes(r)} |")
        body.append("")

    page("apothecary.md", "The Apothecary",
         "Bitter barks, scraped resins, and the things it is wiser not to eat.", body)


# --------------------------------------------------------------------------- the workshop


def workshop(materials, items, processes, recipes, vehicles) -> None:
    classes = vocab("material_classes.json", "classes")
    affordances = vocab("affordances.json", "affordances")
    proc_by_id = named(processes)
    prototypes = {i["base_item"] for i in items if i.get("base_item")}

    body: list[str] = [
        f"**{len(materials)} materials, {len(items)} objects, {len(processes)} ways of making "
        f"and {len(recipes)} recipes.** Everything canon knows about turning one thing into "
        "another.",
        "",
        "A recipe names a `#class` wherever any material of that kind will do, which is why "
        "there are seventy-odd of them rather than one per species. An item marked *prototype* "
        "exists to be inherited from and is never made on its own.",
        "",
        "## Materials, by what they are",
        "",
    ]

    by_class: dict[str, list[dict]] = collections.defaultdict(list)
    for m in materials:
        for c in m.get("classes") or []:
            by_class[c].append(m)
    for c, gloss in classes.items():
        here = by_class.get(c) or []
        if not here:
            continue
        label = gloss.get("label", c) if isinstance(gloss, dict) else c
        names = ", ".join(link(m["id"], "workshop") for m in sorted(here, key=lambda x: x["name"]))
        body.append(f"- **{label}** (`#{c}`) — {names}")
    body.append("")

    # What is made *of* a thing, gathered by walking the recipes backwards. This is the half of
    # a compendium that a list cannot give you: knowing what a reed is matters less than knowing
    # what a reed becomes, and only one of those is written down anywhere in canon.
    #
    # A `#tag` ingredient credits every material carrying that class, because that is what the
    # recipe actually accepts -- a mat asking for `#fibre` is genuinely a use for goat hair.
    used_by: dict[str, list[str]] = collections.defaultdict(list)
    for r in recipes:
        for n in r.get("ingredients") or []:
            if n.get("material"):
                used_by[n["material"]].append(r["id"])
            elif n.get("tag"):
                for m in by_class.get(n["tag"].lstrip("#")) or []:
                    used_by[m["id"]].append(r["id"])

    body.extend(["## The materials themselves", ""])
    for m in materials:
        body.append(f"### {m['name']}")
        body.append("")
        body.append(traits([m.get("rarity", ""), *(m.get("classes") or []), *(m.get("found_in") or [])]))
        body.append("")
        if m.get("notes"):
            body.append(m["notes"])
            body.append("")
        if m.get("won_from"):
            body.append("**Won from** " + ", ".join(link(w) for w in m["won_from"]) + ".")
            body.append("")
        uses = list(dict.fromkeys(used_by.get(m["id"]) or []))
        if uses:
            body.append("**Used in** " + ", ".join(link(u, "workshop") for u in uses) + ".")
            body.append("")

    body.extend(["## Ways of making", "", "| Process | Done at | Needs | |", "|---|---|---|---|"])
    for p in processes:
        at = ", ".join(p.get("performed_at") or []) or "anywhere"
        needs = ", ".join(
            (affordances.get(n) or {}).get("label", n) if isinstance(affordances.get(n), dict) else n
            for n in p.get("needs") or []
        ) or "nothing"
        body.append(f"| **{p['name']}** | {at} | {needs} | {sentence(p.get('notes'))} |")
    body.append("")

    body.extend(["## Recipes, by how they are done", ""])
    by_proc: dict[str, list[dict]] = collections.defaultdict(list)
    for r in recipes:
        by_proc[r.get("process", "")].append(r)
    for pid, here in sorted(by_proc.items(), key=lambda kv: proc_by_id.get(kv[0], {}).get("source_index", 0)):
        body.append(f"### {proc_by_id.get(pid, {}).get('name', pid)}")
        body.append("")
        for r in sorted(here, key=lambda x: x["name"]):
            taught = ", ".join(link(w) for w in r.get("taught_by") or []) or "common knowledge"
            body.append(f"#### {r['name']}")
            body.append("")
            if r.get("known_by"):
                body.append(traits(r["known_by"]))
                body.append("")
            body.append(f"**Makes** {gives(r, 'workshop')}. **Takes** {takes(r, 'workshop')}.")
            body.append("")
            body.append(f"**Taught by** {taught}.")
            body.append("")
            if r.get("notes"):
                body.append(r["notes"])
                body.append("")

    body.extend(["## Objects, by what they are for", "", "| Object | Traits | Made of | |", "|---|---|---|---|"])
    for i in sorted(items, key=lambda x: (x.get("kind", ""), x["name"])):
        tags = [i.get("kind", ""), *(i.get("affords") or [])]
        if i["id"] in prototypes:
            tags.append("prototype")
        of = ", ".join(link(m, "workshop") for m in i.get("materials") or []) or "—"
        body.append(f"| **{i['name']}** | {traits(tags)} | {of} | {sentence(i.get('notes'))} |")
    body.append("")

    if vehicles:
        body.extend(["## Things that carry you", "", "| Craft | Traits | Built of | |", "|---|---|---|---|"])
        for v in vehicles:
            tags = [v.get("kind", ""), *(v.get("crosses") or [])]
            if v.get("capacity"):
                tags.append(f"carries {v['capacity']}")
            of = ", ".join(link(m, "workshop") for m in v.get("materials") or []) or "—"
            body.append(f"| **{v['name']}** | {traits(tags)} | {of} | {sentence(v.get('notes'))} |")
        body.append("")

    page("workshop.md", "The Workshop",
         "What things are made of, and how they are made.", body)


# --------------------------------------------------------------------------- the cookbook


def cookbook(items, recipes, foodways, materials) -> None:
    food = [i for i in items if "eat" in (i.get("affords") or [])]
    food_ids = {i["id"] for i in food}
    dishes = [r for r in recipes if any(o.get("item") in food_ids for o in r.get("outputs") or [])]
    edible = [m for m in materials if set(m.get("classes") or []) & {"produce", "grain", "flesh", "spice", "salt", "oil"}]
    by_dish: dict[str, list[dict]] = collections.defaultdict(list)
    for f in foodways:
        by_dish[f.get("dish", "")].append(f)
    item_name = {i["id"]: i["name"] for i in items}

    body: list[str] = [
        f"**{len(food)} dishes, {len(dishes)} recipes and {len(foodways)} customs.** What this "
        "world eats, and — the part that matters — when and why.",
        "",
        "**The customs are the reason this page exists.** A `foodway` is deliberately not "
        "exported to the game: a dish is an object and ships, but what a loaf *means* on the "
        "night the river comes over the bank is a fact about a people and belongs beside "
        "mythology. That left them read by nothing at all. Here they are read.",
        "",
        "## What is eaten, and what it is for",
        "",
    ]

    for i in sorted(food, key=lambda x: x["name"]):
        body.append(f"### {i['name']}")
        body.append("")
        if i.get("notes"):
            body.append(i["notes"])
            body.append("")
        made_by = [r for r in dishes if any(o.get("item") == i["id"] for o in r.get("outputs") or [])]
        for r in made_by:
            body.append(f"{link(r['id'])} — {takes(r)}.")
            body.append("")
        for f in by_dish.get(i["id"]) or []:
            body.append(f"> **{f['name']}** *({f.get('culture','')})* — {f.get('occasion','')}")
            body.append(">")
            for para in (f.get("meaning") or "").split("\n\n"):
                body.append(f"> {para.strip()}")
                body.append(">")
            body.pop()
            body.append("")

    if edible:
        body.extend(["## What it is made from", "", "| Ingredient | | |", "|---|---|---|"])
        for m in sorted(edible, key=lambda x: x["name"]):
            body.append(f"| {link(m['id'])} | {traits(m.get('classes') or [])} | {sentence(m.get('notes'))} |")
        body.append("")

    page("cookbook.md", "The Cookbook",
         "What is eaten, when it is eaten, and what eating it says.", body)


def check_links() -> list[str]:
    """Every internal link in the books points at a heading that exists.

    A compendium whose cross-references go nowhere is worse than one with none: it invites the
    reader to follow something and then wastes the click. These links are all generated, so the
    only way one breaks is a heading changing shape -- which is exactly the kind of thing nobody
    notices in a 1,300-line generated page, and exactly what a generator should check about its
    own output.

    Compared as slugs rather than as text, because a slug is what both render targets resolve.
    """
    heading = re.compile(r"^#{2,4} (.+)$", re.M)
    ref = re.compile(r"\]\((?:" + re.escape(SITE) + r"/(\w+)\.html)?#([\w-]+)\)")

    have: dict[str, set[str]] = {}
    want: list[tuple[str, str, str]] = []
    for path in sorted(DOCS.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        have[path.stem] = {slug(m) for m in heading.findall(text)}
        for page, anchor in ref.findall(text):
            want.append((path.stem, page or path.stem, anchor))

    broken = [
        f"{page}.md links to {dest}#{anchor}, which is not a heading there"
        for page, dest, anchor in want
        if dest in have and anchor not in have[dest]
    ]

    # And every published page carries the whole nav.
    #
    # This is the failure `book_nav.py` was written to prevent, and adding four books to `PAGES`
    # reintroduced it inside a day: the nav is shared state across five generators, so a new page
    # is only linked from the pages that happen to be regenerated afterwards. Four books shipped
    # reachable and linked from nowhere but each other, exactly as the atlas and timeline once
    # were, and nothing failed -- because from inside the repository it looks done.
    #
    # Checked here rather than in `book_nav.py` because only a thing that reads `docs/` can see
    # it, and this generator already reads all of `docs/`.
    for filename, _page, label in PAGES:
        path = DOCS / filename
        if not path.exists():
            broken.append(f"{filename} is in book_nav.PAGES and does not exist")
            continue
        text = path.read_text(encoding="utf-8")
        for _other, _p, other_label in PAGES:
            # Against the escaped label, because that is what `nav` writes: "Epochs & Events"
            # reaches the page as "Epochs &amp; Events" and searching for the raw ampersand
            # reports every page as broken, which is how this check first read.
            if other_label.replace("&", "&amp;") not in text:
                broken.append(
                    f"{filename} does not link to {other_label!r} -- its nav is stale, so "
                    f"re-run every generator rather than only the one you changed"
                )
    return broken


def main() -> int:
    fauna, flora = load("fauna"), load("flora")
    materials, items = load("materials"), load("items")
    processes, recipes = load("processes"), load("recipes")
    vehicles, foodways = load("vehicles"), load("foodways")

    for group in (fauna, flora, materials, items, processes, recipes, vehicles, load("npcs")):
        for e in group:
            NAMES[e["id"]] = e.get("name", e["id"])

    # Which page carries a reachable entry for a thing. Anything absent stays plain prose --
    # a species is a row in a table rather than an entry, so linking to it would promise a
    # heading that is not there.
    for e in materials:
        ENTRY_PAGE[e["id"]] = "workshop"
    for e in recipes:
        ENTRY_PAGE[e["id"]] = "workshop"
    for e in items:
        if "eat" in (e.get("affords") or []):
            ENTRY_PAGE[e["id"]] = "cookbook"

    bestiary(fauna, flora, load("regions"))
    apothecary(flora, materials, items, recipes)
    workshop(materials, items, processes, recipes, vehicles)
    cookbook(items, recipes, foodways, materials)
    broken = check_links()
    for b in broken:
        print(f"  BROKEN  {b}")
    print(f"\nFour books from {len(fauna) + len(flora)} species and "
          f"{len(materials) + len(items) + len(recipes)} made things.")
    if broken:
        print(f"{len(broken)} cross-reference(s) point at nothing.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
