name: CI

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - 'utils/*.py'
      - 'timeline/timeline.json'
      - 'Dockerfile'
      - 'cartography/overworld.json'
  pull_request:
    branches:
      - main
      - feature/*
    paths:
      - 'utils/*.py'
      - 'timeline/timeline.json'
      - 'Dockerfile'
      - 'cartography/overworld.json'

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t southoftethys .

      - name: Run timeline validation in Docker
        run: docker run --rm southoftethys

      - name: Set up Python (for linting)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install flake8
        run: pip install flake8

      - name: Lint Python scripts
        run: flake8 utils/

  publish-artifacts:
    runs-on: ubuntu-latest
    needs: lint-and-validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate timeline visualization
        run: python utils/generate_timeline_mermaid.py > timeline_mermaid.md

      - name: Publish timeline graph as artifact
        uses: actions/upload-artifact@v4
        with:
          name: timeline-graph
          path: timeline_mermaid.md

      - name: Publish overworld map as artifact
        uses: actions/upload-artifact@v4
        with:
          name: overworld-map
          path: cartography/overworld.json

      # Optionally, run world progression scripts here
      # - name: Progress worldbuilding
      #   run: python utils/progress_world.py