name: CI

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - '.github/workflows/ci.yml'
      - '.gitignore'
      - 'utils/snippet_processor.py'
      - 'Dockerfile'
      - 'cartography/overworld.json'
      - 'CONTEXT.md'

  pull_request:
    branches:
      - main
      - feature/*
    paths:
      - '.github/workflows/ci.yml'
      - '.gitignore'
      - 'utils/snippet_processor.py'
      - 'Dockerfile'
      - 'cartography/overworld.json'
      - 'CONTEXT.md'

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t southoftethys .

      # - name: Run snippet_processor.py to process new snippets
      #   run: python utils/snippet_processor.py > processed_snippets.txt

      - name: Install flake8
        run: pip install flake8

      - name: Lint Python scripts
        run: flake8 utils/

      - name: Run pre-commit checks
        run: pre-commit run --all-files

  publish-artifacts:
    runs-on: ubuntu-latest
    needs: lint-and-validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate timeline visualizations
        run: python utils/generate_timeline_mermaid.py

      - name: Upload timeline summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: timeline_summary
          path: timeline/timeline_summary.md

      - name: Upload timeline mermaid artifact
        uses: actions/upload-artifact@v4
        with:
          name: timeline_mermaid
          path: timeline/timeline_mermaid.md

      - name: Publish processed snippets to the World (ignore this folder)
        uses: actions/upload-artifact@v4
        with:
          name: processed-snippets
          path: 'processed_snippets.txt'

      - name: Publish timeline graph as artifact
        uses: actions/upload-artifact@v4
        with:
          name: timeline-graph
          path: timeline_mermaid.md

      - name: Publish overworld map as artifact
        uses: actions/upload-artifact@v4
        with:
          name: overworld-map
          path: cartography/overworld.json

  deploy:
    runs-on: ubuntu-latest
    needs: publish-artifacts
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy timeline visualizations to docs
        run: |
          mkdir -p docs
          cp timeline/timeline_summary.md docs/index.md
          cp timeline/timeline_mermaid.md docs/timeline_mermaid.md

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs

