name: CI

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - '.github/workflows/ci.yml'
      - '.gitignore'
      - 'utils/snippet_processor.py'
      - 'Dockerfile'
      - 'cartography/overworld.json'
      - 'CONTEXT.md'

  pull_request:
    branches:
      - main
      - feature/*
    paths:
      - '.github/workflows/ci.yml'
      - '.gitignore'
      - 'utils/snippet_processor.py'
      - 'Dockerfile'
      - 'cartography/overworld.json'
      - 'CONTEXT.md'

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t southoftethys .

      - name: Run snippet_processor.py to process new snippets
        run: python utils/snippet_processor.py > processed_snippets.txt

      - name: Install flake8
        run: pip install flake8

      - name: Lint Python scripts
        run: flake8 utils/

  publish-artifacts:
    runs-on: ubuntu-latest
    needs: lint-and-validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate timeline visualization and run world progression scripts here
        run: |
            python utils/generate_timeline_mermaid.py > timeline_mermaid.md
            docker run --rm southoftethys
            python utils/lint_story.py

      - name: Publish processed snippets to Nexus (ignore this folder)
        uses: actions/upload-artifact@v4
        with:
          name: processed-snippets
          path: 'processed_snippets.txt'

      - name: Publish timeline graph as artifact
        uses: actions/upload-artifact@v4
        with:
          name: timeline-graph
          path: timeline_mermaid.md

      - name: Publish overworld map as artifact
        uses: actions/upload-artifact@v4
        with:
          name: overworld-map
          path: cartography/overworld.json

