name: Push Model to Hugging Face

on:
  workflow_dispatch:
  push:
    paths:
      - 'model/**'
      - '.github/workflows/push-hf-model.yml'

jobs:
  push-hf-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Hugging Face CLI
        run: pip install -U "huggingface_hub[cli]"

      - name: Authenticate with Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: hf auth login --token $HF_TOKEN

      - name: Upload model to Hugging Face
        run: hf upload lordlebu/4000BCSaraswaty ./model
