name: Push Model to Hugging Face

on:
  workflow_dispatch:
  push:
    paths:
      - 'model/**'
      - '.github/workflows/push-hf-model.yml'

jobs:
  push-hf-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install huggingface_hub

      - name: Push model to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python <<EOF
          import os
          from huggingface_hub import HfApi, HfHubHTTPError

          def push_model_to_hf(local_folder, repo_id, repo_type="model"):
              token = os.getenv("HF_TOKEN")
              if not token:
                  raise RuntimeError("HF_TOKEN environment variable not set. Get your token from https://huggingface.co/settings/tokens")
              api = HfApi(token=token)
              try:
                  api.upload_folder(
                      folder_path=local_folder,
                      repo_id=repo_id,
                      repo_type=repo_type,
                  )
                  print(f"Successfully pushed {local_folder} to {repo_id}")
              except HfHubHTTPError as e:
                  print(f"HTTP error: {e}")
              except Exception as e:
                  print(f"Unexpected error: {e}")

          if __name__ == "__main__":
              local_folder = "model"
              repo_id = "lordlebu/4000BCSaraswaty"
              push_model_to_hf(local_folder, repo_id)
          EOF
